"""add report tables

Revision ID: 7615f85ec3a7
Revises: 7c6d8e2e0ad6
Create Date: 2026-07-16 21:15:46.216972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7615f85ec3a7'
down_revision: Union[str, Sequence[str], None] = '7c6d8e2e0ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiring_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hiring_project_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='candidatematchstatus', create_type=False), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hiring_project_id'], ['hiring_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hiring_project_id')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('ai_generated', 'edited', 'restored', name='reportversionsource'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['hiring_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_versions')
    op.drop_table('hiring_reports')
    # reportversionsource is created implicitly by report_versions above; drop it here.
    # candidatematchstatus is shared with other tables, so it is intentionally left in place.
    sa.Enum(name='reportversionsource').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
