"""add interview_notes_text to applications

Revision ID: 7c6d8e2e0ad6
Revises: fae179dec35e
Create Date: 2026-07-16 21:10:44.355360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c6d8e2e0ad6'
down_revision: Union[str, Sequence[str], None] = 'fae179dec35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_notes_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'interview_notes_text')
    # ### end Alembic commands ###
