"""candidate matches

Revision ID: d23279a40eaf
Revises: e032cc4c350e
Create Date: 2026-07-14 22:24:41.297181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd23279a40eaf'
down_revision: Union[str, Sequence[str], None] = 'e032cc4c350e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlist_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hiring_project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='candidatematchstatus'), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hiring_project_id'], ['hiring_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hiring_project_id')
    )
    op.create_table('candidate_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='candidatematchstatus'), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_matches')
    op.drop_table('shortlist_recommendations')
    # ### end Alembic commands ###
