"""resume upload redesign

Revision ID: e032cc4c350e
Revises: 39e52c0f30ee
Create Date: 2026-07-14 19:15:13.795709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e032cc4c350e'
down_revision: Union[str, Sequence[str], None] = '39e52c0f30ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.alter_column('applications', 'resume_original_filename', server_default=None)
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('resume_analyses', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('resume_analyses', sa.Column('embedding_status', sa.Enum('pending', 'completed', 'failed', name='resumeanalysisstatus'), nullable=False, server_default='pending'))
    op.add_column('resume_analyses', sa.Column('embedding_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analyses', 'embedding_error_message')
    op.drop_column('resume_analyses', 'embedding_status')
    op.drop_column('resume_analyses', 'extracted_text')
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('applications', 'resume_original_filename')
    # ### end Alembic commands ###
