"""user invite fields

Revision ID: eb9531cad75d
Revises: 6938e67d6675
Create Date: 2026-07-13 23:03:27.742899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb9531cad75d'
down_revision: Union[str, Sequence[str], None] = '6938e67d6675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column('users', sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('invited_by', sa.Integer(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'invite_token')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
